# Generated by Django 3.2.7 on 2021-11-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0003_auto_20211110_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
