# Generated by Django 3.2.7 on 2021-11-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0004_alter_comentario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.CharField(choices=[(0, 'Sin estrellas'), (1, 'Una estrella'), (2, 'Dos estrellas'), (3, 'Tres estrellas'), (4, 'Cuatro estrellas'), (5, 'Cinco estrellas')], max_length=1),
        ),
    ]
