# Generated by Django 3.2.7 on 2021-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0007_alter_comentario_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
