# Generated by Django 3.2.7 on 2021-11-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0010_auto_20211111_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(choices=[(0, '  '), (1, '★'), (2, '★ ★'), (3, '★ ★ ★'), (4, '★ ★ ★ ★'), (5, '★ ★ ★ ★ ★')], default=0),
        ),
    ]
